name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install deps
        run: |
          sudo apt install -y \
            pkg-config \
            zip \
            g++\
            zlib1g-dev \
            unzip \
            python3 \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
      - name: Install bazelisk
        run: |
          wget https://github.com/philwo/bazelisk/archive/$BAZELISK_VERSION.tar.gz -O $BAZELISK_ARCHIVE
          sha256sum -c .github/workflows/SHA256SUMS
          tar xzf $BAZELISK_ARCHIVE -C /tmp
          cd /tmp/bazelisk-$BAZELISK_VERSION
          sudo cp bazelisk.py /usr/local/bin/bazel
        env:
          BAZELISK_ARCHIVE: /tmp/bazelisk.tar.gz
          BAZELISK_VERSION: 8ec9f17a32c6d44abc2dbfb4a86b6b9d559253d0
      - name: Install envoy
        run: |
          curl -sL 'https://getenvoy.io/gpg' | sudo apt-key add -
          sudo add-apt-repository \
            "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable"
          sudo apt-get update && sudo apt-get install -y getenvoy-envoy
          which envoy
          envoy --version
      - name: Build
        run: bazel build //...:all
      - name: Test
        run: bazel test //...:all
